# Data Generation Parameters
data_generation:
  cifar_path: './data'
  output_dir: './data/03_primary' # Changed to a more structured path
  k_candidates: 4

# Training Hyperparameters
training:
  batch_size: 512
  epochs: 2
  learning_rate: 0.0001
  num_classes: 10

pico:
  low_dim: 128
  moco_queue: 8192
  moco_m: 0.999
  proto_m: 0.99
  prot_start: 1 # Start prototype learning early for faster convergence
  loss_weight: 0.5
  conf_ema_range: [0.95, 0.8]